services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8890:8890"
    # env_file:
    #   - .env # Pass variables from the .env file to the container
    # or via environment variables
    environment:
      RELAY: "ws:localhost:7778"
    restart: always

